baseURL = "/"
languageCode = "en-us"
title = "Open Source Quant"
theme = "osquant"

FootnoteReturnLinkContents = "â†‘"


[markup]
  [markup.highlight]
    style = "monokailight"

[markup.goldmark.renderer]
unsafe= true